# This is a basic workflow to help you get started with Actions

name: update_galaxy

# Controls when the action will run.
# Triggers the workflow on push or pull request
# events but only for the devel branch
on:
  push:
    branches:
      - main

jobs:
  update_role:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ansible/ansible-publish-action@main
        with:
          api_key: ${{ secrets.GALAXY_TOKEN }}
